version: '3'
services:
  ansible:
    container_name: ansible
    hostname: ansible
    build: docker/ansible
    tty: true
    working_dir: "/var/data"
    privileged: true
    volumes:
      - .:/var/data

  target01:
    container_name: target01
    hostname: target01
    build: docker/target
    tty: true
    privileged: true

  target02:
    container_name: target02
    hostname: target02
    build: docker/target
    tty: true
    privileged: true

