name: Ansible Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbooks
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            *.yml
          override-deps: |
            ansible==2.9
            ansible-lint==4.3.7
          args: >
            --exclude docker-compose.yml

